version: '3.3'

services:
  app:
    build: "."
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - APIKEY=<YOURKEY>
    ports:
      - "8081:8080"