name: Build and Push to GCR

on:
  push:
    tags:
      - "push*"

# Environment variables available to all jobs and steps in this workflow
#  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
#  GKE_KEY: ${{ secrets.GKE_KEY }}
env:
  GITHUB_SHA: '${{ github.sha }}'
  GITHUB_REF: '${{ github.ref }}'
  IMAGE: 'python:3.9.15-slim'
  REGISTRY_HOSTNAME: 'gcr.io'
  IMAGE_NAME: 'mbti-ckip-bert'
  PROJECT_NAME: 'voiss-353911'


jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, and Publish'
    runs-on: 'ubuntu-latest'
    steps:

    - name: 'Checkout'
      uses: 'actions/checkout@v2'

    # Setup gcloud CLI
    - name: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCR_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'


    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: 'Use gcloud CLI'
      run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
    # Build the Docker image
    - name: 'Build'
      run: |
        export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
        echo $TAG
        docker build -t "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE_NAME":"$TAG" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .
    # Push the Docker image to Google Container Registry
    - name: 'Publish'
      run: |
        export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
        echo $TAG
        docker push "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE_NAME":"$TAG" 
